[database]
db_url = "postgresql://postgres.izmjvmiprlyvyrbikvky:CH5ArjEDWjsv9naT@aws-1-us-east-2.pooler.supabase.com:6543/postgres"

[tiingo]
api_key = "74d79406a6adbd63dfd68b80230cb624ed177ac4"

[ibkr_ga]
flex_token = "578655231785957661588"
query_id = "1303095"
primary_account = "U4686363"

[ibkr_gbe]
flex_token = "578655231785957661588"
query_id = "1303095"
primary_account = "U1250237"